name: mister_frodo
description: a dart client sdk to the https://the-one-api.dev/v2 api
version: 1.0.1
homepage: https://github.com/kumamoto/mister_frodo

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  dio: ^4.0.6
  json_annotation: ^4.6.0
  equatable: ^2.0.5
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_http_formatter: ^2.1.0
  quiver: ^3.1.0
  universal_io: ^2.0.4

dev_dependencies:
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4
  dotenv: ^4.0.1
